---
title: "age_metadata_visualization"
output: html_document
---

# number of samples with age data
```{r}
# n samples with age data
sum(!is.na(dataset21and22$age_years))

# n samples with SRM and age data
sum(!is.na(dataset21and22$age_years) & dataset21and22$SRM_present == TRUE)
```

# histogram of age_years
```{r}

# histogram of "age_years" data (excluding exceptions from "host age")
ggplot(data = dataset21and22, aes(x=dataset21and22$"age_years")) +
  geom_histogram(binwidth = 5, fill = "grey", color = "black") +
  xlab("age in years") +
  ggtitle("Histogram of Host Age (Years)") +
  scale_x_continuous(breaks = seq(0,110, 5)) +
  stat_bin(binwidth = 5, geom="text", aes(label=..count..), vjust=-0.5, size = 3, color="red")

# same histogram, but for samples with SRM_present
ggplot(data = subset(dataset21and22, dataset21and22$SRM_present == TRUE), aes(x = subset(dataset21and22$age_years, dataset21and22$SRM_present == TRUE))) +
geom_histogram(binwidth = 5, fill = "grey", color = "black") +
  xlab("age in years") +
  ggtitle("Histogram of Host Age for Sample with SRM") +
  scale_x_continuous(breaks = seq(0,110, 5)) +
  stat_bin(binwidth = 5, geom="text", aes(label=..count..), vjust=-0.5, size = 3, color="red")

# same as top plot, but fill with SRM_present
ggplot(data = dataset21and22, aes(x=dataset21and22$"age_years", fill = dataset21and22$SRM_present)) +
  geom_histogram(binwidth = 5) +
  xlab("age in years") +
  ggtitle("Histogram of Host Age (Years)") +
  scale_x_continuous(breaks = seq(0,110, 5)) +
  scale_fill_discrete(name = "SRM Present?")

```

# bar plot of binned age ranges
```{r}
# ALL SAMPLES:
# bin: 5 year cutoff
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_5yrCutoff)), aes(x = bin_5yrCutoff)) +
geom_bar(fill = "grey", color = "black") +
geom_text(stat='count', aes(label=..count..), vjust=-0.5, color="red") +
xlab("Age Range (years)") +
ggtitle("Sample Ages: 5 year cutoff for all samples")
# 
# # bin: 9 year range
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_9yrSize)), aes(x = factor(bin_9yrSize, levels = c("[0,10)", "[10,20)", "[20,30)", "[30,40)", "[40,50)", "[50,60)", "[60,70)", "[70,80)", "[80,90)", "[90,100)", "[100,110]")))) +
  geom_bar(fill = "grey", color = "black") +
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, color="red") +
  xlab("Age Range (years)") +
  ggtitle("Sample Ages: 9 year bins")

# Samples with SRM:
# bin: 5 year cutoff
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_5yrCutoff) & dataset21and22$SRM_present == TRUE), aes(x = bin_5yrCutoff)) +
geom_bar(fill = "grey", color = "black") +
geom_text(stat='count', aes(label=..count..), vjust=-0.5, color="red") +
xlab("Age Range (years)") +
ggtitle("Sample Ages: 5 year cutoff for SRM Present samples")

# bin: 9 year range
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_9yrSize) & dataset21and22$SRM_present == TRUE), aes(x = factor(bin_9yrSize, levels = c("[0,10)", "[10,20)", "[20,30)", "[30,40)", "[40,50)", "[50,60)", "[60,70)", "[70,80)", "[80,90)", "[90,100)", "[100,110]")))) +
  geom_bar(fill = "grey", color = "black") +
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, color="red") +
  xlab("Age Range (years)") +
  ggtitle("Sample Ages: 9 year bins for SRM Present samples")

# Compare Samples with and without SRM
# bin: 5 year cutoff
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_5yrCutoff)), aes(x = bin_5yrCutoff, fill = SRM_present)) +
geom_bar() +
  geom_text(stat='count', aes(label=..count..), vjust=-0.5, color="black") +
xlab("Age Range (years)") +
ggtitle("Sample Ages: 5 year cutoff for all samples")

# # bin: 9 year range
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_9yrSize) ), aes(x = factor(bin_9yrSize, levels = c("[0,10)", "[10,20)", "[20,30)", "[30,40)", "[40,50)", "[50,60)", "[60,70)", "[70,80)", "[80,90)", "[90,100)", "[100,110]")), fill = SRM_present)) +
  geom_bar() +
  xlab("Age Range (years)") +
  ggtitle("Sample Ages: 9 year bins for all samples")

```

# barplot of SRM present vs. absent groups by age (binned), as a proportion!
```{r}
# bin: 5 year cutoff
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_5yrCutoff)), aes(x = bin_5yrCutoff, fill = SRM_present)) +
geom_bar(position = "fill") +
xlab("Age Bin (years)") +
ggtitle("Sample Ages: 5 year cutoff for all samples")

# bin: 9 year range
ggplot(data = subset(dataset21and22, !is.na(dataset21and22$bin_9yrSize) ), aes(x = factor(bin_9yrSize, levels = c("[0,10)", "[10,20)", "[20,30)", "[30,40)", "[40,50)", "[50,60)", "[60,70)", "[70,80)", "[80,90)", "[90,100)", "[100,110]")), fill = SRM_present)) +
  geom_bar(position = "fill") +
  xlab("Age Bin (years)") +
  ggtitle("Sample Ages: 9 year bins for all samples")


```

